/** 48 сборных ЧМ-2026 — для сетки альбома на фронте. */
export const WC26_TEAMS = [
  { slug: 'aus', label: 'Австралия' },
  { slug: 'aut', label: 'Австрия' },
  { slug: 'alg', label: 'Алжир' },
  { slug: 'eng', label: 'Англия' },
  { slug: 'arg', label: 'Аргентина' },
  { slug: 'bel', label: 'Бельгия' },
  { slug: 'bih', label: 'Босния и Герцеговина' },
  { slug: 'bra', label: 'Бразилия' },
  { slug: 'hai', label: 'Гаити' },
  { slug: 'gha', label: 'Гана' },
  { slug: 'ger', label: 'Германия' },
  { slug: 'cod', label: 'ДР Конго' },
  { slug: 'egy', label: 'Египет' },
  { slug: 'jor', label: 'Иордания' },
  { slug: 'irq', label: 'Ирак' },
  { slug: 'irn', label: 'Иран' },
  { slug: 'esp', label: 'Испания' },
  { slug: 'cpv', label: 'Кабо-Верде' },
  { slug: 'can', label: 'Канада' },
  { slug: 'qat', label: 'Катар' },
  { slug: 'col', label: 'Колумбия' },
  { slug: 'civ', label: "Кот-д'Ивуар" },
  { slug: 'cuw', label: 'Кюрасао' },
  { slug: 'mar', label: 'Марокко' },
  { slug: 'mex', label: 'Мексика' },
  { slug: 'ned', label: 'Нидерланды' },
  { slug: 'nzl', label: 'Новая Зеландия' },
  { slug: 'nor', label: 'Норвегия' },
  { slug: 'pan', label: 'Панама' },
  { slug: 'par', label: 'Парагвай' },
  { slug: 'por', label: 'Португалия' },
  { slug: 'ksa', label: 'С. Аравия' },
  { slug: 'usa', label: 'США' },
  { slug: 'sen', label: 'Сенегал' },
  { slug: 'tun', label: 'Тунис' },
  { slug: 'tur', label: 'Турция' },
  { slug: 'uzb', label: 'Узбекистан' },
  { slug: 'uru', label: 'Уругвай' },
  { slug: 'fra', label: 'Франция' },
  { slug: 'cro', label: 'Хорватия' },
  { slug: 'cze', label: 'Чехия' },
  { slug: 'sui', label: 'Швейцария' },
  { slug: 'swe', label: 'Швеция' },
  { slug: 'sco', label: 'Шотландия' },
  { slug: 'ecu', label: 'Эквадор' },
  { slug: 'kor', label: 'Ю. Корея' },
  { slug: 'rsa', label: 'ЮАР' },
  { slug: 'jpn', label: 'Япония' },
];
